import { combineReducers } from "redux";
import { UtilityReducer } from "./UtilityReducer";
import { userReducer } from "../data/users";
import { combineForms } from "react-redux-form";
import { formReducer } from "./formReducer";

export const leadForm = {
  name: "",
  email: "",
  firstName: "",
  lastName: "",
  middleName: "",
  company: "",
  whatsAppNumber: "",
  leadType: "",
  subLeadType: "",
  leadSource: "",
  leadStatus: "",
  subLeadSource: "",
  rating: "",
  city: "",
  taluka: "",
  district: "",
  state: "",
  zip: "",
  country: "",
  street: "",
  rtoCode: [],
  cgdCompany: "",
  vehicleNumber: "",
  fuelType: "",
  wheeles: "",
  kitEnquired: "",
  vehicleMek: "",
  vehicleModel: "",
  usage: "",
  vehicleType: "",
  dailyRunning: "",
  registration: "",
  mfg: "",
  chassis: "",
  gstNumber: "",
};

export const userForm = {
  name: "",
  email: "",
  firstName: "",
  lastName: "",
  middleName: "",
  company: "",
  whatsAppNumber: "",
  contactPerson: "",
  leadBackground: "",
  interestIn: "",
  leadType: "",
  subLeadType: "",
  leadSource: "",
  leadStatus: "",
  subLeadSource: "",
  rating: "",
  city: "",
  taluka: "",
  district: "",
  state: "",
  zip: "",
  country: "",
  street: "",
  rtoCode: [],
  cgdCompany: "",
  workshopImages: [],
};

export const leadTaskForm = {
  subject: "",
  priority: "",
  date: "",
  rating: "",
  status: "",
  callResult: "",
  comment: "",
};
const rxFormReducer = combineForms({
  userForm,
  leadForm,
  leadTaskForm,
  egForm: {
    city: "",
    taluka: "",
    district: "",
    state: "",
    zip: "",
    country: "",
    rtoCode: [],
    cgdCompany: "",
  },
  customerForm: {},
  editUserForm: {},
  caseForm: {},
  openSMSForm: {},
});

export const reducers = combineReducers({
  utility: UtilityReducer,
  users: userReducer,
  rxFormReducer,
  formReducer,
});